In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\michelle\Desktop\students.csv')

In [5]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [24]:
df_grp = df.groupby('Gender')

In [25]:
df_grp.describe()

       Hours_Studied                                                    \
               count       mean       std  min   25%   50%   75%   max
Gender
Female         130.0  20.123077  6.266702  2.0  15.0  19.0  25.0  32.0
Male           179.0  19.497207  6.101551  1.0  15.0  20.0  24.0  38.0

       Attendance             ... Physical_Activity      Exam_Score  \
            count       mean  ...               75%  max      count
Gender                        ...
Female      130.0  81.938462  ...               4.0  5.0      130.0
Male        179.0  80.737430  ...               4.0  6.0      179.0


             mean       std   min   25%   50%   75%    max
Gender
Female  67.800000  4.481486  60.0  65.0  67.0  70.0  100.0
Male    67.502793  4.990299  59.0  65.0  67.0  69.0   99.0

[2 rows x 56 columns]

In [26]:
for name, group in df_grp.groups.items():
    print(name)

Female
Male

In [29]:
df = df_grp.get_group('Female')
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
28,16,90,Medium,Medium,No,4,58,Medium,Yes,1,Low,Medium,Public,Neutral,3,No,High School,Moderate,Female,66
73,29,92,Low,Medium,No,4,91,Medium,Yes,2,Medium,Medium,Public,Negative,1,No,Postgraduate,Near,Female,72
94,18,89,High,Medium,Yes,4,73,Medium,Yes,3,High,Medium,Private,Positive,2,No,College,Near,Female,100
188,15,74,Low,High,Yes,4,68,Low,Yes,3,Low,Medium,Public,Positive,3,No,High School,Near,Female,64
199,13,87,High,Low,Yes,4,72,Medium,Yes,2,Medium,High,Public,Neutral,3,No,High School,Moderate,Female,67

In [30]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
28,16,90,Medium,Medium,No,4,58,Medium,Yes,1,Low,Medium,Public,Neutral,3,No,High School,Moderate,Female,66
73,29,92,Low,Medium,No,4,91,Medium,Yes,2,Medium,Medium,Public,Negative,1,No,Postgraduate,Near,Female,72
94,18,89,High,Medium,Yes,4,73,Medium,Yes,3,High,Medium,Private,Positive,2,No,College,Near,Female,100
188,15,74,Low,High,Yes,4,68,Low,Yes,3,Low,Medium,Public,Positive,3,No,High School,Near,Female,64
199,13,87,High,Low,Yes,4,72,Medium,Yes,2,Medium,High,Public,Neutral,3,No,High School,Moderate,Female,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,28,61,High,Medium,Yes,4,92,Low,Yes,1,Medium,High,Private,Neutral,4,No,College,Near,Female,68
6494,14,77,Medium,Medium,Yes,4,81,Low,Yes,3,Medium,Medium,Private,Neutral,3,No,College,NaN,Female,66
6510,29,65,Low,Medium,Yes,4,92,Medium,No,0,Medium,Medium,Private,Positive,4,No,High School,Near,Female,66
6561,28,66,Medium,Low,Yes,4,98,Medium,Yes,0,Medium,High,Public,Positive,3,No,High School,Near,Female,67
6600,12,98,Medium,Low,Yes,4,54,Medium,Yes,2,Medium,High,Private,Neutral,3,No,High School,Near,Female,67

In [83]:
#convert dict into dataframe

eduplanet = {'name':['Xola','Zola','Asakhile','Anganani','Aphiwe','Andiswa'],
             'marks':[36,56,78,23,67,55]}

cohan = {'name':['Xola','Zola','Asakhile','Anganani','Aphiwe','Aaroosa','Tyris', 'Travis', 'Luke'],
             'sports':['basketball','golf','soccer','fishing','rugby','cricket','basketball','golf','soccer']}

edu = pd.DataFrame(eduplanet)
coh = pd.DataFrame(cohan)

In [84]:

coh.head()

       name      sports
0      Xola  basketball
1      Zola        golf
2  Asakhile      soccer
3  Anganani     fishing
4    Aphiwe       rugby

In [85]:
edu.head()

       name  marks
0      Xola     36
1      Zola     56
2  Asakhile     78
3  Anganani     23
4    Aphiwe     67

In [86]:
merged_df = pd.merge(edu,coh,on='name', how='right')
merged_df

       name  marks      sports
0      Xola   36.0  basketball
1      Zola   56.0        golf
2  Asakhile   78.0      soccer
3  Anganani   23.0     fishing
4    Aphiwe   67.0       rugby
5   Aaroosa    NaN     cricket
6     Tyris    NaN  basketball
7    Travis    NaN        golf
8      Luke    NaN      soccer

In [87]:
merged_df['Rank'] = merged_df['marks'].rank(ascending=1, method='min')
merged_df.head()

       name  marks      sports  Rank
0      Xola   36.0  basketball   2.0
1      Zola   56.0        golf   3.0
2  Asakhile   78.0      soccer   5.0
3  Anganani   23.0     fishing   1.0
4    Aphiwe   67.0       rugby   4.0

In [88]:
merged_df.sort_values(['Rank','marks'], ascending=[0,1], inplace=True)

In [89]:
merged_df

       name  marks      sports  Rank
2  Asakhile   78.0      soccer   5.0
4    Aphiwe   67.0       rugby   4.0
1      Zola   56.0        golf   3.0
0      Xola   36.0  basketball   2.0
3  Anganani   23.0     fishing   1.0
5   Aaroosa    NaN     cricket   NaN
6     Tyris    NaN  basketball   NaN
7    Travis    NaN        golf   NaN
8      Luke    NaN      soccer   NaN

In [90]:
def comment(x):
    if x <= 50:
        return "Below Average"
    else:
        return "Above Average"

In [91]:
#Add comment by executing function
merged_df['comment'] = merged_df['marks'].apply(comment)
merged_df.head()

       name  marks      sports  Rank        comment
2  Asakhile   78.0      soccer   5.0  Above Average
4    Aphiwe   67.0       rugby   4.0  Above Average
1      Zola   56.0        golf   3.0  Above Average
0      Xola   36.0  basketball   2.0  Below Average
3  Anganani   23.0     fishing   1.0  Below Average

In [92]:
#write to excel
writer = pd.ExcelWriter(r'C:\Users\michelle\Desktop\students.xlsx')
merged_df.to_excel(writer, index=False, header=False)
writer._save()
writer.close()

In [93]:
#isin()
boolen_series = merged_df['sports'].isin(['basketball','soccer'])
boolen_series.head()
new_df = merged_df[boolen_series]

In [94]:
new_df

       name  marks      sports  Rank        comment
2  Asakhile   78.0      soccer   5.0  Above Average
0      Xola   36.0  basketball   2.0  Below Average
6     Tyris    NaN  basketball   NaN  Above Average
8      Luke    NaN      soccer   NaN  Above Average

In [95]:
#between - returns a range of values defined
boolen_series1 = merged_df['marks'].between(50,80)
merged_df[boolen_series1].head()

       name  marks  sports  Rank        comment
2  Asakhile   78.0  soccer   5.0  Above Average
4    Aphiwe   67.0   rugby   4.0  Above Average
1      Zola   56.0    golf   3.0  Above Average

In [110]:
#check duplicates
bool_series = merged_df['sports'].duplicated(keep=False)
merged_df[bool_series].head()

       name  marks      sports  Rank        comment
2  Asakhile   78.0      soccer   5.0  Above Average
1      Zola   56.0        golf   3.0  Above Average
0      Xola   36.0  basketball   2.0  Below Average
6     Tyris    NaN  basketball   NaN  Above Average
7    Travis    NaN        golf   NaN  Above Average

In [106]:
bool_series

2    False
4    False
1    False
0    False
3    False
5    False
6     True
7     True
8     True
Name: sports, dtype: bool